// Generated by CoffeeScript 1.6.3
var Parser, grammar, jison, parser;

Parser = (require('jison')).Parser;

jison = require('jison');

grammar = {
  comment: 'Binary string to json',
  lex: {
    rules: [["[a-zA-Z]+", "return 'e'"], ["$", "return 'EOF'"], ["\\s", "return 'SPACE'"]]
  },
  operators: [["right", "T"]],
  bnf: {
    E: [["T EOF", "return  $1"]],
    T: [["e SPACE T", "$$ = (function(a, b) { return {key: a, value: b}; })($1, $3)"], ["e", "$$ = $1;"]]
  }
};

parser = new Parser(grammar);

module.exports = parser;
